name: portfolio
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  animated_text_kit: ^4.2.2
  seo: ^0.0.4
  provider: ^6.0.5
  font_awesome_flutter: ^10.3.0
  shimmer_animation: ^2.1.0+1
  url_launcher: ^6.1.7
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:

    - family: Gilroy
      fonts:
        - asset: fonts/GilroyThin.otf
          weight: 100
        - asset: fonts/GilroyUltraLight.otf
          weight: 200
        - asset: fonts/GilroyLight.otf
          weight: 300
        - asset: fonts/GilroyRegular.otf
          weight: 400
        - asset: fonts/GilroyMedium.otf
          weight: 500
        - asset: fonts/GilroySemiBold.otf
          weight: 600
        - asset: fonts/GilroyBold.otf
          weight: 700
        - asset: fonts/GilroyExtraBold.otf
          weight: 800
        - asset: fonts/GilroyBlack.otf
          weight: 900