// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiH5KF8JlMkLeXuqLMnM0vqeY4kluzLdo',
    appId: '1:863328021243:web:0fe7171b17f4d44b999e5e',
    messagingSenderId: '863328021243',
    projectId: 'portfolio-ed6b6',
    authDomain: 'portfolio-ed6b6.firebaseapp.com',
    storageBucket: 'portfolio-ed6b6.firebasestorage.app',
    measurementId: 'G-JC65Q2CSGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjDDkFBP8ZQ74TZnS4AvnNf4Ko76Cg0a0',
    appId: '1:863328021243:android:42b10b27edc9a370999e5e',
    messagingSenderId: '863328021243',
    projectId: 'portfolio-ed6b6',
    storageBucket: 'portfolio-ed6b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJAKCDqv5cwldXq1x81RqZEeacjQT3OdU',
    appId: '1:863328021243:ios:50ab21594601526a999e5e',
    messagingSenderId: '863328021243',
    projectId: 'portfolio-ed6b6',
    storageBucket: 'portfolio-ed6b6.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJAKCDqv5cwldXq1x81RqZEeacjQT3OdU',
    appId: '1:863328021243:ios:50ab21594601526a999e5e',
    messagingSenderId: '863328021243',
    projectId: 'portfolio-ed6b6',
    storageBucket: 'portfolio-ed6b6.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiH5KF8JlMkLeXuqLMnM0vqeY4kluzLdo',
    appId: '1:863328021243:web:b2fc82840a488788999e5e',
    messagingSenderId: '863328021243',
    projectId: 'portfolio-ed6b6',
    authDomain: 'portfolio-ed6b6.firebaseapp.com',
    storageBucket: 'portfolio-ed6b6.firebasestorage.app',
    measurementId: 'G-CY9KK9W5S4',
  );
}
